# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BookCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, author: str=None, year: int=None):  # noqa: E501
        """BookCreate - a model defined in Swagger

        :param title: The title of this BookCreate.  # noqa: E501
        :type title: str
        :param author: The author of this BookCreate.  # noqa: E501
        :type author: str
        :param year: The year of this BookCreate.  # noqa: E501
        :type year: int
        """
        self.swagger_types = {
            'title': str,
            'author': str,
            'year': int
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'year': 'year'
        }
        self._title = title
        self._author = author
        self._year = year

    @classmethod
    def from_dict(cls, dikt) -> 'BookCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookCreate of this BookCreate.  # noqa: E501
        :rtype: BookCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookCreate.


        :return: The title of this BookCreate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookCreate.


        :param title: The title of this BookCreate.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this BookCreate.


        :return: The author of this BookCreate.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BookCreate.


        :param author: The author of this BookCreate.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def year(self) -> int:
        """Gets the year of this BookCreate.


        :return: The year of this BookCreate.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this BookCreate.


        :param year: The year of this BookCreate.
        :type year: int
        """

        self._year = year
